name: moralpain
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '^2.5.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.0
  expandable_text: 2.2.0
  flutter_bloc: ^7.2.0
  logging: ^1.0.2
  url_launcher: ^6.0.12
  uuid: 3.0.5
  moralpainapi:
    path: ../api/


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/questionnaire.json
  fonts:
    - family: LibreFranklin
      fonts:
      - asset: fonts/LibreFranklin-Regular.ttf
      - asset: fonts/LibreFranklin-Bold.ttf
        weight: 700
      - asset: fonts/LibreFranklin-Italic.ttf
        style: italic