on:
  push:
    branches: 
      - main
    
name: Adroid APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    - run: flutter pub get
      working-directory: ./app
    - run: flutter test
      working-directory: ./api
    - run: flutter build apk --debug --split-per-abi
      working-directory: ./app
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/app/outputs/flutter-apk/*.apk"
        tag: ${{GITHUB.SHA}}
        token: ${{ secrets.TOKEN }}